server:
  port: 7777
spring:
  application:
    name: consumer
# 自定义属性
system:
  environment:
    # 隔离环境名称，拼接到topic后，xxx_topic_tianxin，默认空字符串
    name: tianxin
    # 启动隔离，会自动在topic上拼接激活的配置文件，达到自动隔离的效果
    # 默认为true，配置类：EnvironmentIsolationConfig
    isolation: false
rocketmq:
  # 多个NameServer，host:port;host:port，RocketMQProperties
  name-server: 192.168.1.140:9876
  consumer:
    # 配置指定group是否启动监听器 group1.topic1 = false
    listeners:
      # key：group名称
      rocketmq_source_code_group:
        # value：{key: topic名称: value: true/false}
        rocketmq_source_code: true
    # 指定消费组
    group: springboot_consumer_group
    # 指定topic，启动时就会注册
    #topic: springboot_consumer_xxx
    # 一次拉取消息最大值，注意是拉取消息的最大值而非消费最大值
    pull-batch-size: 10
logging:
  level:
    io.netty: ERROR
    RocketmqClient: error